/* Generated By:JavaCC: Do not edit this line. RichMacroDefinitionConstants.java */
package org.richfaces.javacc;

public interface RichMacroDefinitionConstants {

  int EOF = 0;
  int SLASH = 1;
  int LEFT_BRACKET = 2;
  int RIGHT_BRACKET = 3;
  int LITERAL = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\\\\"",
    "\"{\"",
    "\"}\"",
    "<LITERAL>",
  };

}
